[package]
name = "snake"
version = "0.1.0"
authors = ["Ivan Yakushev <iyakushev@quantumbrains.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stdweb = "0.4.20"
rand = "0.7.3"